### ISSUE TITLE
How to change logo?

### ISSUE THREAD

**Issue by KoreMike** [getgrav/grav-skeleton-rtfm-site#5]
I can change colors etc. but I can't find how to change the logo. Is it referenced in a twig file?

**Comment by danielberkompas** [comment]
I also can't seem to figure this out.

**Comment by flaviocopes** [comment]
The logo is defined in https://github.com/getgrav/grav-theme-learn2/blob/develop/templates/partials/logo.html.twig

You can change it there directly (remembering that updating the theme will overwrite the change), or create a child theme (http://learn.getgrav.org/themes/customization#theme-inheritance) and change that Twig file content with your own logo.

**Comment by jadoux** [comment]
Grav is a great idea, unfortunately it needs a lot of refinement, every skeleton takes a different approach at styling and configuring the presentation layer, the standards for such work is almost non-existent, so your logo in one skeleton is stored here, in another one it's stored there, your css is called Bob, his css is called John ... and so on, for the average coders, it's nice, but a real hassle

**Comment by ricardo118** [comment]
@jadoux grav gives full control to the theme makers, and as such some differences will arise. The core team attempts to create standards and best practices to make things but sometimes it's not possible as things change and people work differently. 

In my opinion, Grav's idea is unlike most common CMS out there. By that i mean, it's designed so that coders/developers have a extremely flexible and powerful base for any type of project they have. You can customize and shift Grav to whatever you need it to be. 

Of course, this means its harder for basic users to do their own sites on Grav. Personally, I'm happy as a developer to have a super flexible option instead of having to be stuck with bloated CMS's like wordpress, squarespace, etc

**Comment by jadoux** [comment]
@ricardo118 it is definitely a very promising system, but setting standard for any software architecture, let alone a CMS, is the aim of any architect, in other words, look at IOS vs Android, while IOS is highly standardized, apple products are rarely bloated, Android on the other hand, with its flexibility, gives a lot of room for bloat and disorganization, too much flexibility leads at times to disastrous results

**Comment by HubTode** [comment]
I have to agree with @ricardo118  There is a lot of messaging around GRAV saying that it's easy to use. That is true if you are a seasoned developer. The documentation is a dead end for beginners like me, it's not living up to my hopes. I have spent 20 hours sifting documentation mostly meant for Linux and assuming I already know every path.  Several skeletons contain broken constructs. Manual download of admin into the Windows skeletons just creates fatal errors (so far true with open publishing, x corporation and others).

**Comment by amaurib** [comment]
@HubTode you meant to say that you agree with @jadoux.

**Comment by nounours18200** [comment]
I also agree with **jadoux** too: 100% of the users installing a CMS needs to change the logo, one of the very first task to do to setup a website !
It is always a nightmare to change it, and a long search to find a topic giving a working solution: it is definitely something to correct; most of the users are not developpers, and we lose hours or days...
